### ISSUE TITLE
plz update for v39

### ISSUE THREAD

**Issue by DaRealMonika** [Chiss5618/MonkeyAirship#4]
self explanatory

**Comment by rakunt** [comment]
Not necessarily self-explanatory.
Therefore, a few details:

`[BloonsTD6_Mod_Helper] System.ArgumentOutOfRangeException: Array index may not be negative or above length of the array (Parameter 'index')
   at Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray1.get_Item(Int32 index) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/InteropTypes/Arrays/Il2CppReferenceArray.cs:line 47
   at MonkeyAirship.MonkeyAirship.ModifyBaseTowerModel(TowerModel towerModel) in C:\Users\GGPC\source\repos\MonkeyAirship\MonkeyAirship.cs:line 43
   at BTD_Mod_Helper.Api.Towers.ModTowerHelper.FinalizeTowerModel(ModTower modTower, TowerModel towerModel)
   at BTD_Mod_Helper.Api.Towers.ModTower.Register()
   at BTD_Mod_Helper.Api.Internal.ModContentTask.Coroutine()+MoveNext()`

Accordingt to this MelonLoader doesn't like this line:
` weapons.emission = Game.instance.model.GetTowerFromId("MonkeyAce-004").GetBehaviors<AttackAirUnitModel>()[1].weapons[0].emission;`

**Comment by Chissl** [comment]
Updated for v43
